server:
  port: 8080

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    prefer-ip-address: true

spring:
  application:
    name: EstateApp
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/estateapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Mck050604@}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

api:
  prefix: /api/v1

jwt:
  expiration: 2592000 # 30days
  expiration-refresh-token: 5184000
  secretKey: e672a8b64e2a5ab5da300537341d7af496f0059c56838a9a7c634591d2ad6b71